using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Misfits.Reactor;

[GenerateTypedNameReferences]
public sealed partial class ReactorWindow : FancyWindow
{
    public ReactorWindow()
    {
        RobustXamlLoader.Load(this);

        foreach (var layer in new Control[] { BootLayer, LoginLayer, MainLayer, CrtOverlay })
            LayoutContainer.SetAnchorPreset(layer, LayoutContainer.LayoutPreset.Wide);

        CommandLog.StyleBoxOverride = new StyleBoxFlat(Color.FromHex("#0C1F0E"));
    }
}
