using Content.Shared._Misfits.Reactor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Misfits.Reactor;

[GenerateTypedNameReferences]
public sealed partial class ReactorMonitorWindow : DefaultWindow
{
    public event Action<NetEntity>? OnConnect;

    public ReactorMonitorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ReactorMonitorState state)
    {
        Title = state.MonitorTitle;

        ReactorListContainer.RemoveAllChildren();

        if (state.Reactors.Count == 0)
        {
            ReactorListContainer.AddChild(new Label
            {
                Text = Loc.GetString("reactor-monitor-none"),
                FontColorOverride = Color.Gray,
            });
            return;
        }

        foreach (var entry in state.Reactors)
            ReactorListContainer.AddChild(BuildRow(entry));
    }

    private Control BuildRow(ReactorMonitorEntry entry)
    {
        var row = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1a1a1a") },
        };

        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            Margin = new Thickness(6, 4, 6, 4),
        };

        var textBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        textBox.AddChild(new Label
        {
            Text = entry.Name,
            FontColorOverride = Color.White,
        });

        var statusText = entry.Alarm is { } alarm
            ? Loc.GetString(alarm)
            : $"{entry.State.ToString().ToUpperInvariant()} — {(int) entry.Integrity}% INTEGRITY — {(int) (entry.MaxOutput > 0f ? entry.PowerOutput / entry.MaxOutput * 100 : 0)}% OUTPUT";

        textBox.AddChild(new Label
        {
            Text = statusText,
            FontColorOverride = StatusColor(entry),
        });

        var connectButton = new Button { Text = Loc.GetString("reactor-monitor-connect") };
        connectButton.OnPressed += _ => OnConnect?.Invoke(entry.Reactor);

        box.AddChild(textBox);
        box.AddChild(connectButton);
        row.AddChild(box);

        return row;
    }

    private static Color StatusColor(ReactorMonitorEntry entry)
    {
        if (entry.Alarm != null)
            return Color.Red;

        return entry.State switch
        {
            ReactorState.Melted => Color.Red,
            ReactorState.Scrammed => Color.Orange,
            ReactorState.Online => entry.Integrity <= 33f ? Color.Red : entry.Integrity <= 66f ? Color.Yellow : Color.LightGreen,
            _ => Color.Gray,
        };
    }
}
