using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Reactor;

[GenerateTypedNameReferences]
public sealed partial class ReactorWindow : FancyWindow
{
    private static readonly ResPath BootLogoPath = new("/Textures/_Misfits/Interface/Paper/paper_heading_vault14_green.png");

    public ReactorWindow()
    {
        RobustXamlLoader.Load(this);

        foreach (var layer in new Control[] { BootLayer, LoginLayer, MainLayer, CrtOverlay })
            LayoutContainer.SetAnchorPreset(layer, LayoutContainer.LayoutPreset.Wide);

        CommandLog.StyleBoxOverride = new StyleBoxFlat(Color.FromHex("#0C1F0E"));

        var resourceCache = IoCManager.Resolve<IResourceCache>();
        if (resourceCache.TryGetResource<TextureResource>(BootLogoPath, out var logoResource))
        {
            BootLogo.Texture = logoResource.Texture;
            LoginLogo.Texture = logoResource.Texture;
        }
    }
}
