using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Medical.Cryogenics;
using Content.Shared.Mobs;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Medical.Cryogenics.UI;

[GenerateTypedNameReferences]
public sealed partial class CryoPodWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly IResourceCache _cache;
    private EntityUid _spriteViewEntity;
    private Dictionary<TargetBodyPart, TargetIntegrity>? _body;

    private static readonly EntProtoId BodyView = "AlertSpriteView";

    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;

    public event Action<ReagentId, bool>? OnTransferReagent;

    public event Action<bool>? OnSetRunning;

    public CryoPodWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();
        _cache = IoCManager.Resolve<IResourceCache>();

        _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
        {
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Torso, ChestButton },
            { TargetBodyPart.Groin, GroinButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        foreach (var (part, button) in _bodyPartControls)
        {
            button.MouseFilter = MouseFilterMode.Stop;
            button.OnPressed += _ => SelectBodyPart(part);
        }

        RunningButton.OnToggled += args => OnSetRunning?.Invoke(args.Pressed);
    }

    private void SelectBodyPart(TargetBodyPart part)
    {
        var status = _body != null && _body.TryGetValue(part, out var integrity)
            ? HumanizeEnumName(integrity.ToString())
            : Loc.GetString("cryo-pod-window-unknown");

        PartNameLabel.Text = Loc.GetString("cryo-pod-window-selected-part", ("part", HumanizeEnumName(part.ToString())), ("status", status));
    }

    private static string HumanizeEnumName(string name)
    {
        var sb = new System.Text.StringBuilder();
        for (var i = 0; i < name.Length; i++)
        {
            if (i > 0 && char.IsUpper(name[i]))
                sb.Append(' ');
            sb.Append(name[i]);
        }
        return sb.ToString();
    }

    public void UpdateState(CryoPodBoundUserInterfaceState state)
    {
        var hasPatient = state.Patient != null;
        NoPatientLabel.Visible = !hasPatient;
        PatientContainer.Visible = hasPatient;
        _body = state.Body;

        if (hasPatient)
        {
            var patientEntity = _entityManager.GetEntity(state.Patient!.Value);

            var isHumanoid = _entityManager.HasComponent<TargetingComponent>(patientEntity);
            foreach (var (_, button) in _bodyPartControls)
                button.Visible = isHumanoid;

            PatientSprite.SetEntity(SetupIcon(state.Body) ?? patientEntity);
            PatientSprite.Visible = true;
            NoDataTex.Visible = false;

            PatientNameLabel.Text = state.PatientName ?? Loc.GetString("cryo-pod-window-unknown");
            PatientStateLabel.Text = state.PatientState switch
            {
                MobState.Alive => Loc.GetString("cryo-pod-window-patient-alive"),
                MobState.Critical or MobState.SoftCritical => Loc.GetString("cryo-pod-window-patient-critical"),
                MobState.Dead => Loc.GetString("cryo-pod-window-patient-dead"),
                _ => Loc.GetString("cryo-pod-window-patient-unknown"),
            };
            PartNameLabel.Text = string.Empty;

            if (state.Temperature is { } temperature)
            {
                var coldEnough = temperature <= CryoPodComponent.HealingTemperatureThreshold;
                TemperatureLabel.Text = Loc.GetString(
                    coldEnough ? "cryo-pod-window-temperature-cold" : "cryo-pod-window-temperature-warm",
                    ("temperature", (int) temperature));
                TemperatureLabel.FontColorOverride = coldEnough ? Color.Green : Color.Yellow;
            }
            else
            {
                TemperatureLabel.Text = Loc.GetString("cryo-pod-window-unknown");
                TemperatureLabel.FontColorOverride = null;
            }

            TotalDamageLabel.Text = state.TotalDamage?.ToString() ?? Loc.GetString("cryo-pod-window-unknown");

            BleedingLabel.Visible = state.Bleeding;
            if (state.Bleeding)
            {
                BleedingLabel.Text = Loc.GetString("cryo-pod-window-bleeding");
                BleedingLabel.FontColorOverride = Color.Red;
            }

            DrawDamageGroups(state.DamagePerGroup, state.DamagePerType);
        }
        else
        {
            DamageGroupsContainer.RemoveAllChildren();
        }

        RunningButton.Pressed = state.Running;
        RunningButton.Text = Loc.GetString(state.Running ? "cryo-pod-window-running-stop" : "cryo-pod-window-running-start");

        BeakerEjectButton.Text = state.HasBeaker
            ? Loc.GetString("cryo-pod-window-eject-button")
            : Loc.GetString("cryo-pod-window-insert-button");
        BeakerNameLabel.Text = state.HasBeaker
            ? state.BeakerName ?? Loc.GetString("cryo-pod-window-unknown")
            : Loc.GetString("cryo-pod-window-no-beaker");

        DrawReagentRows(BeakerReagentsContainer, state.BeakerReagents, fromBuffer: false, showButtons: state.HasBeaker);

        BufferVolumeLabel.Text = $"{state.BufferVolume}u / {state.BufferMaxVolume}u";
        DrawReagentRows(BufferReagentsContainer, state.BufferReagents, fromBuffer: true, showButtons: state.HasBeaker);
    }
    private EntityUid? SetupIcon(Dictionary<TargetBodyPart, TargetIntegrity>? body)
    {
        if (body is null)
            return null;

        if (!_entityManager.Deleted(_spriteViewEntity))
            _entityManager.QueueDeleteEntity(_spriteViewEntity);

        _spriteViewEntity = _entityManager.Spawn(BodyView);

        if (!_entityManager.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var sprite))
            return null;

        var spriteEnt = new Entity<SpriteComponent?>(_spriteViewEntity, sprite);

        var layer = 0;
        foreach (var (bodyPart, integrity) in body)
        {
            var enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart) ?? "Unknown";
            var enumValue = (int) integrity;
            var rsi = new SpriteSpecifier.Rsi(new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{enumName.ToLowerInvariant()}.rsi"), $"{enumName.ToLowerInvariant()}_{enumValue}");
            if (!_spriteSystem.TryGetLayer(spriteEnt, layer, out _, false))
                _spriteSystem.AddTextureLayer(spriteEnt, _spriteSystem.Frame0(rsi));
            else
                _spriteSystem.LayerSetTexture(spriteEnt, layer, _spriteSystem.Frame0(rsi));
            _spriteSystem.LayerSetScale(spriteEnt, layer, new Vector2(3f, 3f));
            layer++;
        }
        return _spriteViewEntity;
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private void DrawDamageGroups(Dictionary<string, FixedPoint2>? damagePerGroup, Dictionary<string, FixedPoint2>? damagePerType)
    {
        DamageGroupsContainer.RemoveAllChildren();

        if (damagePerGroup == null)
            return;

        foreach (var (damageGroupId, damageAmount) in damagePerGroup.OrderByDescending(kv => kv.Value))
        {
            if (damageAmount <= FixedPoint2.Zero || !_prototypes.TryIndex<DamageGroupPrototype>(damageGroupId, out var group))
                continue;

            var groupTitleText = Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", group.LocalizedName),
                ("amount", damageAmount));

            var groupContainer = new BoxContainer
            {
                Align = BoxContainer.AlignMode.Begin,
                Orientation = BoxContainer.LayoutOrientation.Vertical,
            };

            groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, damageGroupId));
            DamageGroupsContainer.AddChild(groupContainer);

            if (damagePerType == null)
                continue;

            foreach (var type in group.DamageTypes)
            {
                if (!damagePerType.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                if (!_prototypes.TryIndex<DamageTypePrototype>(type, out var typeProto))
                    continue;

                var damageString = Loc.GetString(
                    "health-analyzer-window-damage-type-text",
                    ("damageType", typeProto.LocalizedName),
                    ("amount", typeAmount));

                groupContainer.AddChild(new Label { Text = damageString.Insert(0, " · ") });
            }
        }
    }

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower()),
        });

        rootContainer.AddChild(new Label { Text = text });

        return rootContainer;
    }

    private static readonly Color RowColorOdd = Color.FromHex("#1B1B1E");
    private static readonly Color RowColorEven = Color.FromHex("#202025");

    private void DrawReagentRows(BoxContainer container, List<ReagentQuantity> reagents, bool fromBuffer, bool showButtons)
    {
        container.RemoveAllChildren();

        if (reagents.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("cryo-pod-window-empty"),
                Margin = new Thickness(4),
            });
            return;
        }

        for (var i = 0; i < reagents.Count; i++)
        {
            container.AddChild(BuildReagentRow(reagents[i], i, fromBuffer, showButtons));
        }
    }

    private Control BuildReagentRow(ReagentQuantity reagentQuantity, int rowIndex, bool fromBuffer, bool showButtons)
    {
        var name = reagentQuantity.Reagent.Prototype;
        var reagentColor = Color.White;
        if (_prototypes.TryIndex<ReagentPrototype>(reagentQuantity.Reagent.Prototype, out var reagentProto))
        {
            name = reagentProto.LocalizedName;
            reagentColor = reagentProto.SubstanceColor;
        }

        var rowContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(4, 2),
            Children =
            {
                new Label { Text = $"{name}: " },
                new Label
                {
                    Text = $"{reagentQuantity.Quantity}u",
                    StyleClasses = { "LabelSubText" },
                },
                new Control { HorizontalExpand = true },
                new PanelContainer
                {
                    VerticalExpand = true,
                    MinWidth = 4,
                    Margin = new Thickness(0, 1),
                    PanelOverride = new StyleBoxFlat { BackgroundColor = reagentColor },
                },
            },
        };

        if (showButtons)
        {
            var button = new Button
            {
                Text = Loc.GetString(fromBuffer ? "cryo-pod-window-withdraw-button" : "cryo-pod-window-deposit-button"),
                StyleClasses = { "OpenLeft" },
            };
            var reagentId = reagentQuantity.Reagent;
            button.OnPressed += _ => OnTransferReagent?.Invoke(reagentId, fromBuffer);
            rowContainer.AddChild(button);
        }

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = rowIndex % 2 == 1 ? RowColorOdd : RowColorEven },
            Children = { rowContainer },
        };
    }
}
